# Generated by Django 5.2 on 2025-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="telefone",
            field=models.CharField(
                help_text="Telefone de contato", max_length=11, verbose_name="Telefone"
            ),
        ),
    ]
