# Generated by Django 5.2 on 2025-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="telefone",
            field=models.CharField(
                help_text="Telefone de contato", max_length=15, verbose_name="Telefone"
            ),
        ),
    ]
