# Generated by Django 5.2 on 2025-06-11 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "uuid_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "data_de_entrada",
                    models.DateField(
                        help_text="Data de entrada do veículo na oficina",
                        verbose_name="Data de Entrada",
                    ),
                ),
                (
                    "data_de_entrega",
                    models.DateField(
                        blank=True,
                        help_text="Data prevista/efetiva de entrega do veículo",
                        null=True,
                        verbose_name="Data de Entrega",
                    ),
                ),
                (
                    "orcamento",
                    models.IntegerField(
                        default=0,
                        help_text="Valor do orçamento em centavos",
                        verbose_name="Orçamento",
                    ),
                ),
                (
                    "descricao_problema",
                    models.TextField(
                        help_text="Descrição do problema relatado pelo cliente",
                        verbose_name="Descrição do Problema",
                    ),
                ),
                (
                    "descricao_concerto",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do serviço realizado",
                        null=True,
                        verbose_name="Descrição do Conserto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDA", "Concluída"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "quilometragem",
                    models.FloatField(
                        help_text="Quilometragem atual do veículo",
                        verbose_name="Quilometragem",
                    ),
                ),
                (
                    "pk_id_carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_orders",
                        to="vehicles.vehicle",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "db_table": "services_serviceorder",
                "ordering": ["-data_de_entrada"],
            },
        ),
    ]
