# Generated by Django 5.2 on 2025-06-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="descricao_concerto",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descrição detalhada do serviço realizado",
                verbose_name="Descrição do Conserto",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="descricao_problema",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descrição do problema relatado pelo cliente",
                verbose_name="Descrição do Problema",
            ),
        ),
    ]
