# Generated by Django 5.2 on 2025-07-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_serviceorder_descricao_concerto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="quilometragem",
            field=models.IntegerField(
                help_text="Quilometragem atual do veículo", verbose_name="Quilometragem"
            ),
        ),
    ]
