# Generated by Django 5.2 on 2025-05-29 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "uuid_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(
                        help_text="Marca do veículo",
                        max_length=50,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Modelo do veículo",
                        max_length=50,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "ano",
                    models.PositiveIntegerField(
                        help_text="Ano do veículo", verbose_name="Ano"
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        help_text="Placa do veículo",
                        max_length=8,
                        unique=True,
                        verbose_name="Placa",
                    ),
                ),
                (
                    "pk_id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "db_table": "vehicles_vehicle",
                "ordering": ["placa"],
            },
        ),
    ]
