# Generated by Django 5.2 on 2025-05-29 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "uuid_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da peça ou material",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "estoque",
                    models.IntegerField(
                        default=0,
                        help_text="Quantidade em estoque",
                        verbose_name="Estoque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça/Material",
                "verbose_name_plural": "Peças e Materiais",
                "db_table": "inventory_product",
                "ordering": ["nome"],
            },
        ),
    ]
