# Generated by Django 5.2 on 2025-06-11 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "uuid_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "data_do_agendamento",
                    models.DateTimeField(
                        help_text="Data e hora do agendamento",
                        verbose_name="Data do Agendamento",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        help_text="Nome do responsável pelo agendamento",
                        max_length=100,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "pk_id_carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="vehicles.vehicle",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "db_table": "scheduling_appointment",
                "ordering": ["data_do_agendamento"],
            },
        ),
    ]
