# Generated by Django 5.2 on 2025-06-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="pk_id_ordem_de_servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="services.serviceorder",
                verbose_name="Ordem de Serviço",
            ),
        ),
    ]
